.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. luk_qt test_luk_qt
clean: FORCE
	$(MAKE) -C .. luk_qt_clean test_luk_qt_clean
check: FORCE
	$(MAKE) -C .. test_luk_qt_check
luk-qt luk-qt.exe: FORCE
	 $(MAKE) -C .. luk_qt
